#######################  EUREKA CONFIGURATION  #######################
eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://service-registry:8761/eureka

#######################  SPRING CLOUD CONFIGURATION  #######################
spring:
  cloud:
    discovery:
      enabled: 'true'
    gateway:
      httpclient:
        response-timeout: 2s
        connect-timeout: '1000'
      discovery:
        locator:
          lower-case-service-id: 'true'
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411

#######################  SERVER CONFIGURATION  #######################
server:
  port: '8083'

#######################  LOGGING CONFIGURATION  #######################
logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            filter:
              factory: TRACE

#######################  SECURITY CONFIGURATION  #######################
kanwise:
  security:
    authentication-route: http://user-service/auth/token/validate
    open-api-endpoints:
      - /auth/register
      - /auth/login
      - /auth/password/reset/request
      - /auth/password/request/forgotten
      - /auth/password/reset/forgotten
      - /auth/password/reset
      - /auth/registration/otp/sms
  cors:
    allowed-origins:
      - http://localhost:4200