#######################  SERVER CONFIGURATION  #######################
server:
  port: '8085'
#######################  SPRING CONFIGURATION  #######################
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: 'true'
  application:
    name: report-service
  #######################  ZIPKIN CONFIGURATION  #######################
  zipkin:
    base-url: http://zipkin:9411
  #######################  QUARTZ CONFIGURATION  #######################
  quartz:
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            useProperties: 'false'
            isClustered: 'true'
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
            dataSource: myDS
            clusterCheckinInterval: '1000'
            misfireThreshold: '60000'
          scheduler:
            instanceName: MyClusteredScheduler
            instanceId: AUTO
          dataSource:
            myDS:
              URL: jdbc:postgresql://postgres:5432/quartz
              maxConnections: '5'
              validationQuery: select 0 from dual
              driver: org.postgresql.Driver
              user: kanwise
              password: kanwise
          threadPool:
            threadPriority: '5'
            threadCount: '25'
            class: org.quartz.simpl.SimpleThreadPool
    job-store-type: jdbc

  #######################  DATASOURCE CONFIGURATION  #######################
  liquibase:
    change-log: /changelog-quartz.xml
    password: kanwise
    user: kanwise
    url: jdbc:postgresql://postgres:5432/quartz
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  datasource:
    password: kanwise
    url: jdbc:postgresql://postgres:5432/report
    username: kanwise
  #######################  KAFKA CONFIGURATION  #######################
  kafka:
    bootstrap-servers: kafka:9092
    topic-names:
      NOTIFICATION_EMAIL: notification-email


#######################  PDF CONFIGURATION  #######################
pdf.generated:
  paths:
    PERSONAL: "/app/resources/generated/personal/"
    PROJECT: "/app/resources/generated/project/"

pdf.template:
  names:
    PERSONAL: "personal-report.html"
    PROJECT: "project-report.html"

#######################  KANWISE CONFIGURATION  #######################
kanwise:
  #######################  URL CONFIGURATION  #######################
  url:
    public-urls:
      - '**'
  #######################  SPACES CONFIGURATION  #######################
  digitalocean:
    spaces:
      serviceEndpoint: ${DO_SPACES_ENDPOINT}
      names:
        reports: ${DO_SPACES_BUCKET}
      secretKey: ${DO_SPACES_SECRET_KEY}
      signingRegion: ${DO_SPACES_REGION}
      accessKey: ${DO_SPACES_ACCESS_KEY}
  #######################  AUTHENTICATION CONFIGURATION  #######################
  filter:
    ommited:
      authentication:
        - path: "/subscriber"
          method: "POST"
  #######################  DIRECTORY CONFIGURATION  #######################
  directory:
    report-templates: "/app/resources/templates-report-pdf"

#######################  EUREKA CONFIGURATION  #######################
eureka:
  client:
    fetch-registry: 'true'
    service-url:
      defaultZone: http://service-registry:8761/eureka
    register-with-eureka: 'true'