package com.kanwise.kanwise_service.model.notification;

public enum ProjectNotificationType {
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    PROJECT_ASSIGNED,
    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_REMOVED,
    PROJECT_JOIN_REQUEST_CREATED,
    PROJECT_JOIN_REQUEST_ACCEPTED,
    PROJECT_JOIN_REQUEST_REJECTED,
    PROJECT_TASK_CREATED,
    PROJECT_TASK_UPDATED,
    PROJECT_TASK_DELETED,
    PROJECT_TASK_ASSIGNED
}
