package com.kanwise.notification_service.model.email;

public enum EmailMessageType {
    ACCOUNT_CREATED,
    ACCOUNT_BLOCKED,
    PROJECT_JOIN_REQUEST_REJECTED,
    PROJECT_JOIN_REQUEST_ACCEPTED,
    NEW_TASK_ASSIGNED,
    PASSWORD_RESET,
    PASSWORD_CHANGED,
    USER_INFORMATION_CHANGED,
    PERSONAL_REPORT,
    PROJECT_REPORT
}
